### ISSUE TITLE
request for the dataset

### ISSUE THREAD

**Issue by EVIG-ZJU** [wukaoliu/CVPR2020-HAttMatting#16]
hello
 I have sent you an email for your dataset. Could please check your mailbox. 
Expect your reply

**Comment by FreeHeart111** [comment]
Thank you very much.



At 2020-12-07 18:27:19, "EVIG-ZJU" <notifications@github.com> wrote:

hello
I have sent you an email for your dataset. Could please check your mailbox.
Expect your reply

**Comment by skeras** [comment]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email (shipeilong715@163.com）? thanks！  
best regards!

**Comment by wkias** [comment]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email (2782546116@qq.com）? thanks！
best regards!

**Comment by Shk-aftab** [comment]
Hey, I want the dataset for my final year project, please sent the dataset link to my email (shaikhaftab139@gmail.com)

**Comment by florids** [comment]
hello,
this project is very meaningful ,so i want the dataset for my research. Could please check your mailbox.
Expect your reply

**Comment by luoww1992** [comment]
@EVIG-ZJU 
 I want the dataset for a new training, can you share me the dataset link to my email (luoww1992@sina.com)
thanks !

**Comment by zzl-gray** [comment]
Hey, thank you for your project! But I want the dataset for a new training, can you share me the dataset link to my email (274015732@qq.com)?
thanks again!!!

**Comment by jasonlbx13** [comment]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email (602465307@qq.com）? thanks！
best regards!

**Comment by wuyefeilin** [comment]
Hi, your work is awesome. I need your dataset for research, can you share me the dataset link to my email (642982169@qq.com)

**Comment by 1239238241** [comment]
Hi, I am very interested in your work, could you share me the dataset link for me doing my research? Thanks
1239238241@QQ.COM

**Comment by ntquyen11** [comment]
Hi, your project is great. Now I am researching about human matting image so can you share me your dataset to my email (quyen.nt172779@sis.hust.edu.vn)?

**Comment by BalinLin** [comment]
Hi, thanks for the great job. I need the dataset for research.
Please send me the link of dataset. Thank you!!
my email: m10815105@gapps.ntust.edu.tw

**Comment by marcojoao** [comment]
Amazing work, can you please share with me your dataset?
my email: marco.funstuff@gmail.com
Thank you

**Comment by IvanFei** [comment]
Hi, Amazing work,  can you please share with me your dataset?
my email: huangfeifei5943@sina.cn
Thank you

**Comment by ntquyen11** [comment]
Dear Mr/Mrs
Sorry about that I don't check the mail frequently so I saw your email.
Here is a link Human Matting https://www.kaggle.com/ntquyen11/matting . If
you don't open this link, please send an email to me then I will send my
dataset to you

**Comment by yuhaoliu7456** [comment]
Hi please send us an email for accessing the dataset.

**Comment by wukaoliu** [comment]
Hi, please send us an email for accessing the dataset.

**Comment by jasonlbx13** [comment]
Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月11日(星期天) 中午12:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wukaoliu/CVPR2020-HAttMatting] request for the dataset (#16)





 
Hi please send us an email for accessing the dataset.

**Comment by jasonlbx13** [comment]
Thanks a lot!
***@***.***


------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月11日(星期天) 中午12:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wukaoliu/CVPR2020-HAttMatting] request for the dataset (#16)





 
Hi please send us an email for accessing the dataset.

**Comment by longsy316** [comment]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email?  (longsy316@163.com）thanks！
best regards!

**Comment by DYJNG** [comment]
Hi, this project is so awesome. 
I need this dataset for research.
Could you share me the dataset link for me doing my research? Thank you!
My email is 592381378@qq.com
Best regards!
@wukaoliu

**Comment by onlyhantenghao** [comment]
Hi，Sorry to bother you，may i have a copy of datasets for just  research, please？thanks a lot， this is my email ：（484415064@qq.com） @wukaoliu

**Comment by zackzhao1** [comment]
> 
> 
> Hi please send us an email for accessing the dataset.

Hi，may i have a link of datasets for research, please？thanks a lot， my email is zhaojialei@iristar.com.cn  @wukaoliu

**Comment by Iaua-aae12** [comment]
Hi, this project is so awesome. I need this dataset for research. 
Can you sent dataset link to my email? Thank you!
My email is syusan0510@gmail.com
@wukaoliu

**Comment by 1239238241** [comment]
兄弟，这论文不是我写的呀



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 3, 2021 15:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wukaoliu/CVPR2020-HAttMatting] request for the dataset (#16)




 
Hi, this project is so awesome. I need this dataset for research.
 Can you sent dataset link to my email? Thank you!
 My email is ***@***.***
 @wukaoliu
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ascendpoet** [comment]
Hi！ I'm studying matting now. Could you give me this database？Thank you very much! My email is 455912207@qq.com.  @yuhaoliu7456 @wukaoliu

**Comment by 1239238241** [comment]
这论文不是我的兄弟



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 23, 2021 11:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuhaoliu7456/CVPR2020-HAttMatting] request for the dataset (#16)




 
Hi！ I'm studying matting now. Could you give me this database？Thank you very much! My email is ***@***.***  @yuhaoliu7456 @wukaoliu
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vietnamican** [comment]
> Hi please send us an email for accessing the dataset.
Could you give me this database？Thank you very much! My email is vietnamican@gmail.com

**Comment by docShen** [comment]
I like this project!
I need dataset distinctions 646 for coding.
Could you share me the dataset link to me? Thank you so much!
My email is 110094558@qq.com

**Comment by yangjian1218** [comment]
申请邮箱是多少? 没找到

**Comment by mingqizhang** [comment]
Hi, Could you share me the dataset link for me? Thank you!
My email is 461799796@qq.com

**Comment by mutsuyuki** [comment]
I love this work, can you please share with me your dataset?
my email: [mutsuyuki.tanaka@gmail.com](mailto:mutsuyuki.tanaka@gmail.com)
Thank you!

**Comment by marshall-dteach** [comment]
I also want to get your datasets for some interesting research, can you sent it to matting@buaa.edu.cn, Thanks a lot!

**Comment by saurabh-shandilya** [comment]
@FreeHeart111 @yuhaoliu7456 

Great work with video matting. Can you please share the dataset at sshandilya@gmail.com

Thanks!
