### ISSUE TITLE
咱们来建立一个qq讨论群吧

### ISSUE THREAD

**Issue by newjavaer** [wukaoliu/CVPR2020-HAttMatting#19]
欢迎加入Deep Learning Matting QQ群：261457538；

**Comment by vietnamican** [comment]
Can you open a room in slack, skype,... or sth. I can't sign up a QQ account.

**Comment by newjavaer** [comment]
@vietnamican  Ohh，I think it's diffcult for me. But  I think we can contact by the Telegram.

**Comment by vietnamican** [comment]
Thank you, please remind me when you created a group in telegram. Or can you send me your telegram account right here. I'll contact with you.

**Comment by vietnamican** [comment]
@newjavaer Can you give me a download link via gmail: vietnamican@gmail.com

**Comment by newjavaer** [comment]
@vietnamican Hi,Which download link?Oh,I forget to tell you.I can't log on Telegram now because of some force majeure.But our QQ grounp is growing .If you can join our qq group,I will tell how to download QQ International.I am glad to contact with you.We can also communicate with E-mail about some matting questions.And my e-mail is chestnut1xxx@gmail.com

**Comment by vietnamican** [comment]
I'm afraid I can't signup a QQ account. I've tried for several days, and I can't find QQ Internaltional in GG playstore too! If I can donwload QQ International, can I signup an account?

**Comment by newjavaer** [comment]
@vietnamican I think you can find the other methods to download the QQ instead of downloading in GG playstore.If you can download ,I think it's easy to signup an account.

**Comment by wozijitaibenle** [comment]
您好？问一下这个代码现在都还没有开源吗？
