### ISSUE TITLE
Suitable for Mobile Matting?

### ISSUE THREAD

**Issue by InternetMaster1** [wukaoliu/CVPR2020-HAttMatting#2]
Thank you for the amazing work!

I had two questions :

1) Is this algorithm suitable for performing image matting on a mobile device (like Android) or it would be too heavy?

2) Can this code be used for commercial work?

3) Would you be providing the code to train & evaluate? I believe this performs matting without a trimap?

**Comment by yuhaoliu7456** [comment]
1. yes
2. no
3. yes

**Comment by cfoster0** [comment]
AFAICT, the code was released under the permissive MIT license, which _does_ permit commercial use, contra #2.
