### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Sweetest316** [wukaoliu/CVPR2020-HAttMatting#26]
I like this project!
I need dataset distinctions 646 for coding.
Could you share me the dataset link to me? Thank you so much!
My email is 1483328931@qq.com

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
