### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by JayLin1996** [wukaoliu/CVPR2020-HAttMatting#29]
Hi~!Mr.blogger.
I like this project!
I need dataset distinctions 646 for coding.
Could you share me the dataset link to me? Thank you so much!
My email is 1996_jaylin@sina.cn

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.

**Comment by JayLin1996** [comment]
To yuhao：
 
 
 
Thans for your reply.


 



 Best regard！
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 12月9日 23:12，YuhaoLiu ***@***.***> 写道： 
   
  Our dataset is available at  Distinctions-646.
