### ISSUE TITLE
How to determinate which object should be extracted

### ISSUE THREAD

**Issue by sjf18** [wukaoliu/CVPR2020-HAttMatting#3]
Hi, thanks for your great work,
i have a question, how does your HattMatting determinate which object you wanted should be extracted, for example, what if i want the person, not the animal, for in my vision the animal is nearly eauql to the person, but you have no trimap input.
<img width="1139" alt="Snipaste_2020-06-15_11-16-48" src="https://user-images.githubusercontent.com/30466896/84614802-cd240100-aef9-11ea-9aa9-2f7a283ddcf6.png">

**Comment by 99991** [comment]
Another example: Why does the network decide to pick the sieve and not the people behind it?

![Screenshot_2020-06-19 Attention-Guided Hierarchical Structure Aggregation for Image Matting - Qiao_Attention-Guided_Hierarc (1)](https://user-images.githubusercontent.com/18725165/85106891-47f85f00-b20d-11ea-9e43-fcfb805ddf07.png)

My guess would be that the network is biased to pick the largest object around the center of the image and maybe it has learned some way to tell which object is in front.

Will the model or the training code be released? It should be easy enough to test then.

**Comment by vjleo** [comment]
Can't wait to test this!!

Any ETA on the code?

**Comment by mozpp** [comment]
I think it is impossible to mat with single rgb input. I hope the code will prove that I am wrong.

**Comment by fyang235** [comment]
> I think it is impossible to mat with single rgb input. I hope the code will prove that I am wrong.

can't agree more !
