### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by HZNUJeffreyRen** [wukaoliu/CVPR2020-HAttMatting#30]
hello，can you share the Distinctions-646 dataset？
my email is renzhenfeng@shuwen.com

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
