### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by wanglingyun95** [wukaoliu/CVPR2020-HAttMatting#32]
hello，can you share the Distinctions-646 dataset？Thanks
wanglingyun9502@gmail.com

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
