### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by KouseiHongqing** [wukaoliu/CVPR2020-HAttMatting#33]
hi，can you share the Distinctions-646 dataset？
my email is 279749773@qq.com
thanks!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
