### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by LYM1111** [wukaoliu/CVPR2020-HAttMatting#34]
hi，can you share the Distinctions-646 dataset？
my email is 1482736846@qq.com 
thanks!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
