### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by yataoz** [wukaoliu/CVPR2020-HAttMatting#35]
Hi, thanks for the awesome work! I've sent a dataset request to your email. Could you check your gmail.com inbox? Really appreciate it!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
