### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by MasaTate** [wukaoliu/CVPR2020-HAttMatting#36]
Hello.

I requested to share your nice dataset by email.
Could you check your email inbox?

Thank you.

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
