### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by zhanghongyong123456** [wukaoliu/CVPR2020-HAttMatting#37]
您好，可以分享一下您的数据集吗？我的邮箱是：
1037645638@qq.com
非常感谢您的对抠像领域作出的贡献！

**Comment by MangekyoSasuke** [comment]
您好，请问拿到Distinctions-646数据集了吗

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
