### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by YYLCyylc** [wukaoliu/CVPR2020-HAttMatting#40]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email ([293588017@qq.com](mailto:293588017@qq.com)）? thanks！
best regards!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
