### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by zengpeng175** [wukaoliu/CVPR2020-HAttMatting#41]
您好，师兄，我是17届的师弟，这项工作太棒了，是做matting避不开的研究对象，如果方便能否获得数据集，我的邮箱是 631811495@qq.com  时刻期待师兄的回复和指导，祝开心！

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
