### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by FishHe** [wukaoliu/CVPR2020-HAttMatting#42]
作者您好，您的HAttMatting是研究该领域时重要的参考算法，您是否方便提供给我使用的数据集，我的邮箱是：
zhangdengsu@whu.edu.cn

**Comment by yellowyi9527** [comment]
同求数据集 247418361@qq.com

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.

**Comment by yellowyi9527** [comment]
感谢
