### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by hmchuong** [wukaoliu/CVPR2020-HAttMatting#43]
Hi,

Thank you for your great work! I would like to get the dataset as a benchmark for my research project. Could you send me the dataset via my email chuonghm@umd.edu ?

Thank you,

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
