### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by TClan8023** [wukaoliu/CVPR2020-HAttMatting#44]
Hi，最近在做trimap-free自然场景抠图的研究，不知是否方便分享下数据集，我的邮箱是1094859220@qq.com。谢谢

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
