### ISSUE TITLE
Dataset Request :)

### ISSUE THREAD

**Issue by skuley** [wukaoliu/CVPR2020-HAttMatting#46]
Hi,

Thank you for your great research!

I am working on high resolution pixel level SOD segementation and I would like to ask if you could kindly send datasets you've trained.

My email: [skuleyandpotato@gmail.com](mailto:skuleyandpotato@gmail.com)

Thank you,

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
