### ISSUE TITLE
请求数据

### ISSUE THREAD

**Issue by syn0419** [wukaoliu/CVPR2020-HAttMatting#47]
您好，感谢您作出的突出贡献！
基于研究需要，想申请一下数据集，如果可以，还烦请您分享至邮箱623873639@qq.com，不胜感激！

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
