### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by ProfessorUncle** [wukaoliu/CVPR2020-HAttMatting#48]
Hi,this project is awesome,I want use this dataset just for research,can you sent dataset link to my email ([1337995064@qq.com]）? thanks！
best regards!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
