### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by z1246456493** [wukaoliu/CVPR2020-HAttMatting#49]
Hi, 
      I have been researching a project on character photography in film and television recently. Would you please share your data set? My email address is:1246456493@qq.com. 
             thank you

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
