### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by greentea903** [wukaoliu/CVPR2020-HAttMatting#50]
Thank you for the great work! 

I want use Dinstinctions-646 just for research, 
Could you share the dataset with me?

My email address is: 

Thank you.

**Comment by maoyj2333** [comment]
have you got the datasets?

**Comment by linix01** [comment]
Thank you for the great work!

I want use Dinstinctions-646 just for research,
Could you share the dataset with me?
My email address is: fuchilin@163.com

thank you!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
