### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by MangekyoSasuke** [wukaoliu/CVPR2020-HAttMatting#52]
您好，读完后非常敬佩您的工作和研究水平，想要Dinstinctions-646数据集做研究，不作商业目的，烦请分享数据集至z839984698@163.com，谢谢！！！

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
