### ISSUE TITLE
dataset requirement

### ISSUE THREAD

**Issue by hpyanming** [wukaoliu/CVPR2020-HAttMatting#53]
Thank you for the great work!

I want use Dinstinctions-646 just for research,
Could you share the dataset with me?

My email address is: [hp_yanming@163.com]

Thank you very much!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
