### ISSUE TITLE
Requirement for dataset

### ISSUE THREAD

**Issue by felix-ky** [wukaoliu/CVPR2020-HAttMatting#54]
Hi, could you please share the dataset?
my email is felixky@zju.edu.cn
many thanks!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
