### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Jerry-Master** [wukaoliu/CVPR2020-HAttMatting#55]
To whom it may concern,

My team requires this dataset for research, can you send it to joseperez2000@hotmail.es

Thanks in advance,
Jose

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
