### ISSUE TITLE
Dataset request 

### ISSUE THREAD

**Issue by BoredWait** [wukaoliu/CVPR2020-HAttMatting#56]
Hi, could you please share the dataset?
my email is [1353363226@qq.com](mailto:1353363226@qq.com)
many thanks!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
