### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by Wickked-swag** [wukaoliu/CVPR2020-HAttMatting#57]
作者您好，
读完该论文后十分钦佩您的工作能力与想法，同时想要Dinstinctions-646数据集做更多的研究，不作商业目的，烦请分享数据集至wangjiasheng@nwafu.edu.cn ，十分感谢！！！

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
