### ISSUE TITLE
dataset requirement

### ISSUE THREAD

**Issue by bluebirdin** [wukaoliu/CVPR2020-HAttMatting#58]
Hi, your work is really wonderfull.
Could you please share me with the dataset?
I want to use it for research.
My email is 1473589707@qq.com.
Thanks a lot!

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
