### ISSUE TITLE
Request data set

### ISSUE THREAD

**Issue by LukeyWang** [wukaoliu/CVPR2020-HAttMatting#60]
I am very interested in your results. I also need such a data set for my current research. Can you send me a copy? Thank you very much. wangdp23@mails.jlu.edu.cn

**Comment by yuhaoliu7456** [comment]
Our dataset is available at <a href="https://drive.google.com/file/d/1ljJkWONPfJzylkZg_1HaGRoaRaaiAxRu/view?usp=sharing"> Distinctions-646</a>.
